import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Landing Page</title>
        <meta name="Next Landing Page" content="Generated by Simon Lanza Fiorito" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div class="text-white bg-black h-auto p-20 font-serif">
          <p class="text-fluoyellow font-semibold p-4 flex justify-start text-left">La mejor opcion de hoy en Landing Pages</p>
          <h1 class="text-5xl font-extrabold p-4 flex justify-center text-center" >Flexible y rapido para tu empresa</h1>
          <p class="p-2 flex justify-center text-center">Somos un equipo chico de programadores que nos especializamos en crear Landing Pages dinamicas, completas e informativas.</p>
          <p class="p-2 flex justify-center text-center">Cree su Landing Page ahora y comienze a ver resultados</p>
          <div  class="flex justify-center p-4">
            <button class="bg-fluoyellow p-2 w-32 h-14 rounded-lg text-black font-semibold">Hablemos</button>
          </div>
        </div>
        <div>

        </div>
      </header>
      <body>
        <div class="text-black bg-white h-auto p-5 font-serif grid grid-cols-1 grid-rows-3 h-64 phone:grid-cols-2">
          <p class="p-3 text-4xl flex justify-center" >
            HTML 5
            <img class="w-12 h-14 mx-3" src="/html5.png"></img>
          </p>
          <p class="p-3 text-4xl flex justify-center" >
            CSS3
            <img class="w-12 h-14 mx-3" src="/css3.png"></img>
          </p>
          <p class="p-3 text-4xl flex justify-center" >
            JavaScript
            <img class="w-14 h-14 mx-3" src="/javascript.png"></img>
          </p>
          <p class="p-3 text-4xl flex justify-center" >
            React Js
            <img class="w-12 h-14 mx-3" src="/react.png"></img>
          </p>
          <p class="p-3 text-4xl flex justify-center" >
            Next Js
            <img class="w-12 h-14 mx-3" src="/nextjs.svg"></img>
          </p>
          <p class="p-3 text-4xl flex justify-center" >
            Tailwind Css
            <img class="w-12 h-14 mx-3" src="/tailwindcss.svg"></img>
          </p>
        </div>
        <div class="text-black bg-grey h-auto p-16 font-serif">
          <p class="text-blue italic text-lg p-3">La nueva forma</p>
          <h2 class="flex justify-center text-center text-4xl font-semibold p-3">Cree su pagina perzonalizada al 100% con nosotros</h2>
          <p class="text-lg p-3 italic">Ya no necesita ni una empresa gigante, ni miles de dolares para crearla.</p>
          <p class="text-lg p-3 italic">Es hora de buscar nuevas alternativas, un nuevo futuro.</p>
        </div>
        <div class="text-white bg-black h-auto p-20 font-serif">
          <p class="text-fluoyellow text p-3 text-lg">El mundo cambia</p>
          <h2 class="font-semibold text-4xl flex items-center text-center p-3">Que tu empresa o emprendimiento no se quede atras</h2>
          <div class="grid grid-cols-1 grid-rows-auto  p-8 mt-16 tablet:grid-cols-2">
              <p class="text-5xl">
                10.000+
                <p class="text-lg max-w-sm">Empresas o emprendimientos usan una pagina web profesional en Bs As.</p>
              </p>
              <p class="text-5xl">
                37%
                <p class="text-lg max-w-sm">Incrementan las visitas, interacciones o ventas  luego de cambiar una pagina rustica por una  atractiva</p>
              </p>
              <div class="justify-center tablet:col-span-2">
                <img class="w-screen" src="/mundo.jpg"/>
              </div>
          </div>
        </div>
      </body>
      <footer class="grid grid-cols-2 p-8 justify-items-center bg-black text-white">
        <h2 class="grid justify-center mb-2 text-lg font-semibold text-fluoyellow">Contacto</h2>
        <h2 class="grid justify-center mb-2 text-lg font-semibold text-fluoyellow">Sobre mi</h2>
        <h3 class="mb-1">e-Mail: simonlanza99@gmail.com</h3>
        <a class="mb-1  hover:text-fluoyellow" href="https://github.com/simonlanza">GitHub</a>
        <h3>numero: 1131425613</h3>
        <a class=" hover:text-fluoyellow" href="https://www.linkedin.com/in/simon-lanza-4ab8351aa/">LinkedIn</a>
      </footer>
    </div>
  )
}
